language: python
sudo: false

python:
  - "3.4"
  - "3.6"

install:
  - mkdir lib
  - pip install -r requirements.txt

script:
  - ./localization.sh
  - export PYTHONPATH=$PYTHONPATH:.:./lib
  - py.test translator/tests -v --cov translator --durations=10

after_success:
- coveralls
